// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"Code/src/swagger/go-user/models"
)

// NewCreateUserRequestParams creates a new CreateUserRequestParams object
//
// There are no default values defined in the spec.
func NewCreateUserRequestParams() CreateUserRequestParams {

	return CreateUserRequestParams{}
}

// CreateUserRequestParams contains all the bound params for the create user request operation
// typically these are obtained from a http.Request
//
// swagger:parameters createUserRequest
type CreateUserRequestParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*This text will appear as description of your request body.
	  In: body
	*/
	Body *models.User
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateUserRequestParams() beforehand.
func (o *CreateUserRequestParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.User
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("body", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
