// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"Code/src/swagger/go-user/models"
)

// GetUserRequestOKCode is the HTTP code returned for type GetUserRequestOK
const GetUserRequestOKCode int = 200

/*GetUserRequestOK This text will appear as description of your response body.

swagger:response getUserRequestOK
*/
type GetUserRequestOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewGetUserRequestOK creates GetUserRequestOK with default headers values
func NewGetUserRequestOK() *GetUserRequestOK {

	return &GetUserRequestOK{}
}

// WithPayload adds the payload to the get user request o k response
func (o *GetUserRequestOK) WithPayload(payload *models.User) *GetUserRequestOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user request o k response
func (o *GetUserRequestOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserRequestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetUserRequestDefault This text will appear as description of your error response body.

swagger:response getUserRequestDefault
*/
type GetUserRequestDefault struct {
	_statusCode int
	/*Error code.

	 */
	Code int64 `json:"code"`
	/*Error message.

	 */
	Message string `json:"message"`
}

// NewGetUserRequestDefault creates GetUserRequestDefault with default headers values
func NewGetUserRequestDefault(code int) *GetUserRequestDefault {
	if code <= 0 {
		code = 500
	}

	return &GetUserRequestDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get user request default response
func (o *GetUserRequestDefault) WithStatusCode(code int) *GetUserRequestDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get user request default response
func (o *GetUserRequestDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithCode adds the code to the get user request default response
func (o *GetUserRequestDefault) WithCode(code int64) *GetUserRequestDefault {
	o.Code = code
	return o
}

// SetCode sets the code to the get user request default response
func (o *GetUserRequestDefault) SetCode(code int64) {
	o.Code = code
}

// WithMessage adds the message to the get user request default response
func (o *GetUserRequestDefault) WithMessage(message string) *GetUserRequestDefault {
	o.Message = message
	return o
}

// SetMessage sets the message to the get user request default response
func (o *GetUserRequestDefault) SetMessage(message string) {
	o.Message = message
}

// WriteResponse to the client
func (o *GetUserRequestDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header code

	code := swag.FormatInt64(o.Code)
	if code != "" {
		rw.Header().Set("code", code)
	}

	// response header message

	message := o.Message
	if message != "" {
		rw.Header().Set("message", message)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
