// Code generated by go-swagger; DO NOT EDIT.

// Package restapi awesome.
//
//  Documentation of our awesome API.
//  Schemes:
//    http
//    https
//  Host: some-url.com
//  BasePath: /
//  Version: 0.1.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
