// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUserRequestParams creates a new GetUserRequestParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUserRequestParams() *GetUserRequestParams {
	return &GetUserRequestParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserRequestParamsWithTimeout creates a new GetUserRequestParams object
// with the ability to set a timeout on a request.
func NewGetUserRequestParamsWithTimeout(timeout time.Duration) *GetUserRequestParams {
	return &GetUserRequestParams{
		timeout: timeout,
	}
}

// NewGetUserRequestParamsWithContext creates a new GetUserRequestParams object
// with the ability to set a context for a request.
func NewGetUserRequestParamsWithContext(ctx context.Context) *GetUserRequestParams {
	return &GetUserRequestParams{
		Context: ctx,
	}
}

// NewGetUserRequestParamsWithHTTPClient creates a new GetUserRequestParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUserRequestParamsWithHTTPClient(client *http.Client) *GetUserRequestParams {
	return &GetUserRequestParams{
		HTTPClient: client,
	}
}

/* GetUserRequestParams contains all the parameters to send to the API endpoint
   for the get user request operation.

   Typically these are written to a http.Request.
*/
type GetUserRequestParams struct {

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get user request params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserRequestParams) WithDefaults() *GetUserRequestParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get user request params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserRequestParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get user request params
func (o *GetUserRequestParams) WithTimeout(timeout time.Duration) *GetUserRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user request params
func (o *GetUserRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user request params
func (o *GetUserRequestParams) WithContext(ctx context.Context) *GetUserRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user request params
func (o *GetUserRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user request params
func (o *GetUserRequestParams) WithHTTPClient(client *http.Client) *GetUserRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user request params
func (o *GetUserRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get user request params
func (o *GetUserRequestParams) WithName(name string) *GetUserRequestParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get user request params
func (o *GetUserRequestParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
